#!/bin/bash
# vim: ts=4 sw=4 ai noet
# $Id$
#
# Copyright (C) 2008, Robert Nelson. Licensed under GPLv2.
# By Robert Nelson.
#

test -n "$DEBUG_EXEC" && set -x

TOOLDIR=/usr/share/vzpkg2

. ${TOOLDIR}/apt-functions

log4 Started $0 $*

# Since we can't figure out if updates are needed without
# doing everything required to actually do the update we'll
# pretend updates are required.

exit 1
