#!/bin/bash
# vim: ts=4 sw=4 ai noet
# $Id$
#
# Copyright (C) 2008, Robert Nelson. Licensed under GPLv2.
# By Robert Nelson.
#

test -n "$DEBUG_EXEC" && set -x

TOOLDIR=/usr/share/vzpkg2

. ${TOOLDIR}/apt-functions

log4 Started $0 $*

CMD=$1
shift

PACKAGES=$*

case $CMD in
--installed)	ARGS='-W --showformat=\${package}-\${version}\\n';;
--info)			ARGS='-s';;
--files)		ARGS='-L';;
--search)		ARGS='--search';;
*)
esac

$VZCTL exec $VEID dpkg-query $ARGS $PACKAGES

exit $?
