#!/bin/bash
# vim: ts=4 sw=4 ai noet
# $Id$
#
# Copyright (C) 2008, Robert Nelson. Licensed under GPLv2.
# By Robert Nelson.
#

TOOLDIR=/usr/share/vzpkg

. ${TOOLDIR}/functions

function apt_cleanup()
{
	log4 "Doing cleanup"
	if mount | grep $VE_ROOT/var/cache/apt/archives > /dev/null 2>&1; then
		log4 Unmounting $VE_ROOT/var/cache/apt/archives
		umount $VE_ROOT/var/cache/apt/archives
	fi
}
