#!/bin/bash
# vim: ts=4 sw=4 ai noet
# $Id$
#
# Copyright (C) 2008, Robert Nelson. Licensed under GPLv2.
# By Robert Nelson.
#
# Portions originally:
# Copyright (C) 2003, 2004, 2005, 2006 by SWsoft. Licensed under GNU GPL.
#

test -n "$DEBUG_EXEC" && set -x

TOOLDIR=/usr/share/vzpkg2

. ${TOOLDIR}/apt-functions

log4 Started $0 $*

$VZCTL exec $VEID apt-get -y update
$VZCTL exec2 $VEID apt-get -y install $*

exit $?
