#!/bin/bash
# $Id: vzosname,v 1.1 2005/10/25 05:46:07 kir Exp $
#
# vzosname - "canonize" given OS template name.
#
# Copyright (C) 2005, SWsoft. Licensed under QPL.
# By Kir Kolyshkin.

TOOLDIR=/usr/share/vzpkg
#DEBUG_LEVEL=4

. ${TOOLDIR}/functions

OST=`ost2full $1` || exit 1
set $OST
OSNAME=$1
OSVER=$2
OSSET=$3
OSARCH=$4
echo $OSNAME-$OSVER-$OSARCH-$OSSET
