#!/bin/bash
# vim: ts=4 sw=4 ai noet
# $Id$
#
# Copyright (C) 2008, Robert Nelson. Licensed under GPLv2.
# By Robert Nelson.
#
# Portions originally:
# Copyright (C) 2005, SWsoft. Licensed under GNU GPL.
# By Kir Kolyshkin.
#
# vzosname - "canonize" given OS template name.
#

TOOLDIR=/usr/share/vzpkg2
#DEBUG_LEVEL=4

. ${TOOLDIR}/functions

OST=`ost2full $1` || exit 1
set $OST
OSNAME=$1
OSVER=$2
OSSET=$3
OSARCH=$4
echo $OSNAME-$OSVER-$OSARCH-$OSSET
