#!/bin/bash
# vim: ts=4 sw=4 ai noet
# $Id$
#
# Copyright (C) 2008, Robert Nelson. Licensed under GPLv2.
# By Robert Nelson.
#

test -n "$DEBUG_EXEC" && set -x

TOOLDIR=/usr/share/vzpkg

. ${TOOLDIR}/functions

export -f find_template_config_file

get_veid $1
export VEID VE_ROOT VE_PRIVATE

# Sanity checks
STATUS=`$VZCTL status $VEID` || abort "Can't get status for VE $VEID: " \
	"vzctl status failed with code $?"
echo $STATUS | grep -qw "exist" || abort "VE $VEID not exist!"
echo $STATUS | grep -qw "running" || abort "VE $VEID not running; " \
	"you should start it first"

get_ve_os_template $VEID || abort "Can't get OSTEMPLATE for VE $VEID"
TEMPLATE=`get_vz_var TEMPLATE`
OST=`ost2full $OSTEMPLATE` || abort "No such OS template: $OSTEMPLATE"
set $OST
OS_NAME=$1
OS_VER=$2
OS_SET=$3
OS_ARCH=$4
TEMPLATE_DIR=$5
export OS_NAME OS_VER OS_SET OS_ARCH TEMPLATE_DIR
check_ost_exists $OS_NAME $OS_VER $OS_SET $OS_ARCH || exit 1

PACKAGER=`get_packager` || exit 1

# Run it
log4 exec $TOOLDIR/$PACKAGER-update
exec $TOOLDIR/$PACKAGER-update
