#!/bin/bash
# $Id: vzpkgadd,v 1.4 2006/05/11 14:20:35 kir Exp $
# Copyright (C) 2005, SWsoft. Licensed under QPL.
#
# Simple wrapper for vzrpm -U

# Handle options
case $1 in
	-f|--force)
		OPTS="--force --nodeps"
		shift
		;;
esac

VEID=$1
shift
exec /usr/bin/vzrpm $VEID $OPTS -U $*
