#!/bin/bash
# $Id: vzpkgadd,v 1.3 2005/08/10 12:41:33 kir Exp $
# Copyright (C) 2005, SWsoft. Licensed under QPL.
#
# Simple wrapper for vzrpm -U

# Handle options
case $1 in
	-f|--force)
		OPTS="--force --nodeps"
		shift
		;;
esac

VPSID=$1
shift
exec /usr/bin/vzrpm $VPSID $OPTS -U $*
