#!/bin/bash
# vim: ts=4 sw=4 ai noet
# $Id$
#
# Copyright (C) 2008, Robert Nelson. Licensed under GPLv2.
# By Robert Nelson.
#

test -n "$DEBUG_EXEC" && set -o xtrace

TOOLDIR=/usr/share/vzpkg2

. ${TOOLDIR}/yum-functions

log4 Started $0 $*

# This is a workaround for a buggy rpm install in Debian etch.
log4 Creating /var/lib/rpm in HN
test -d /var/lib/rpm || {
	mkdir /var/lib/rpm
	chown rpm:rpm /var/lib/rpm
	chmod 0755 /var/lib/rpm
}

log4 Creating /var/log
mkdir -p $VE_ROOT/var/log

log4 Creating /var/lib/yum and /var/cache/yum
mkdir -p $VE_ROOT/var/lib/yum
mkdir -p $VE_ROOT/var/cache/yum

log4 Creating /var/lib/rpm and /var/lock/rpm
mkdir -p $VE_ROOT/var/lib/rpm
mkdir -p $VE_ROOT/var/lock/rpm

mkdir -p $VE_ROOT/dev
mknod $VE_ROOT/dev/null c 1 3
chmod 0666 $VE_ROOT/dev/null

# install gpg keys
import_gpgkeys

# Returns list of packages to be installed into VE.
file=`find_template_config_file $OS_SET.list` || \
	abort "List of packages for $OS_SET not found!"

LIST=`egrep -v '^#|^[[:space:]]*$' < $file` || exit $?

run_yum install yum $LIST || abort "yum failed with $? exit code"

rm -f $VE_ROOT/var/lib/rpm/__db.0*
