#!/bin/bash
# vim: ts=4 sw=4 ai noet
# $Id$
#
# Copyright (C) 2008, Robert Nelson. Licensed under GPLv2.
# By Robert Nelson.
#

test -n "$DEBUG_EXEC" && set -o xtrace

TOOLDIR=/usr/share/vzpkg

. ${TOOLDIR}/yum-functions

log4 Started $0 $*

run_yum check-update
rc=$?

if test $rc -eq 0; then
	exit 0
elif test $rc -eq 100; then
	exit 1
else
	abort "Command yum check-update failed with $rc exit code"
fi
