#!/bin/bash
# vim: ts=4 sw=4 ai noet
# $Id$
#
# Copyright (C) 2008, Robert Nelson. Licensed under GPLv2.
# By Robert Nelson.
#

test -n "$DEBUG_EXEC" && set -o xtrace

TOOLDIR=/usr/share/vzpkg

. ${TOOLDIR}/yum-functions

log4 Started $0 $*

$VZCTL exec2 $VEID yum erase $*

exit $?
